### ISSUE TITLE
EQ3BLE.discover is not a function

### ISSUE THREAD

**Issue by adamkalicinscy** [maxnowack/node-eq3ble#2]
i have node 7.4.0
After running 

```
var EQ3BLE = require('eq3ble');
EQ3BLE.discover((device) => {
  device.connectAndSetup().then(() => {
    // ...
  })
})
```

i got:

```
TypeError: EQ3BLE.discover is not a function
    at Object.<anonymous> (/home/pi/Projects/tempble/index.js:10:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

Is there something wrong with inheritance?

**Comment by felixfischer** [comment]
+1

**Comment by maxnowack** [comment]
I think the root cause of this issue exists in the package which is used for the bluetooth communication: https://github.com/sandeepmistry/noble-device
Maybe someone can verify this …

**Comment by felixfischer** [comment]
I got the module to work with node 7.4.0 using babel, like this (main script is index.js):

```
npm install --save babel-cli babel-preset-env
sudo ./node_modules/babel-cli/bin/babel-node.js --presets env ./index.js
```

**Comment by maxnowack** [comment]
This doesn't has something todo with the specific node version nor with the noble-device package. This package uses import/export style module exports. So if you're using the default `require` function to import modules, you have to do it like this:
````js
const EQ3BLE = require('eq3ble').default
````
